import { describe, it, expect } from 'vitest';
import { makeFakeFactory } from './helpers/fake-factory.js';
import { completionHandler } from '../src/commands/completion.js';
import { ValidationError } from '../src/lib/errors.js';

// The completion script is generated by walking the live Commander tree, so it
// must reflect commands added anywhere without a manual list update.
describe('completion (dynamic, tree-walked)', () => {
  it('rejects an unsupported shell', async () => {
    const env = makeFakeFactory();
    await expect(completionHandler(env.factory, {}, ['tcsh'])).rejects.toThrow(ValidationError);
  });

  it('bash script includes newer nouns (catalog, node, source-control)', async () => {
    const env = makeFakeFactory();
    await completionHandler(env.factory, {}, ['bash']);
    const out = env.stdout();
    for (const noun of ['catalog', 'node', 'source-control', 'variable', 'project']) {
      expect(out).toContain(noun);
    }
  });

  it('reflects newly-added verbs (execution delete, catalog sync, workflow transfer)', async () => {
    const env = makeFakeFactory();
    await completionHandler(env.factory, {}, ['bash']);
    const out = env.stdout();
    expect(out).toMatch(/catalog\)[\s\S]*sync show reset/);
    expect(out).toMatch(/execution\)[\s\S]*delete/);
    expect(out).toMatch(/workflow\)[\s\S]*transfer/);
  });

  it('generates all four shells without error', async () => {
    for (const shell of ['bash', 'zsh', 'fish', 'powershell']) {
      const env = makeFakeFactory();
      await completionHandler(env.factory, {}, [shell]);
      expect(env.stdout().length).toBeGreaterThan(50);
    }
  });
});
