import { promises as fs, existsSync, readFileSync } from 'node:fs';
import path from 'node:path';
import { loadCatalog, type NodeCatalog, type NodeSchema, type ParamType } from '@trngthnh369/n8n-workflow-validator';
import { getConfigDir } from './config.js';
import { dedupeLatest, type NodeDescription, type NodeProperty } from './node-catalog.js';

/**
 * Bridges the live instance node catalog (`node-catalog.ts` → /types/nodes.json)
 * into the offline validator's `NodeCatalog` schema, so `workflow validate`
 * (and the deploy-path auto-validate) can Layer-6 param-check against the ~400+
 * node types the instance actually runs — incl. community nodes — instead of
 * the 36-node bundled snapshot.
 *
 * The validator stays decoupled: it already accepts `options.catalog`, so
 * n8nctl loads the synced catalog per active profile and passes it in. No
 * validator changes / version bump needed.
 */

/** Where a profile's synced catalog lives. */
export function syncedCatalogPath(profileName: string): string {
  const safe = profileName.replace(/[^a-zA-Z0-9_-]/g, '_') || 'default';
  return path.join(getConfigDir(), 'catalogs', `node-catalog.${safe}.json`);
}

/** n8n property `type` → the validator's coarse ParamType. Conservative. */
function toParamType(t: string | undefined): ParamType {
  switch (t) {
    case 'string':
    case 'options': // single choice; value is a string (enum captured separately)
    case 'dateTime':
    case 'color':
    case 'resourceLocator':
    case 'credentialsSelect':
      return 'string';
    case 'number':
      return 'number';
    case 'boolean':
      return 'boolean';
    case 'multiOptions':
      return 'array';
    case 'collection':
    case 'fixedCollection':
    case 'json':
      return 'object';
    default:
      return 'any';
  }
}

function versionsOf(n: NodeDescription): number[] {
  if (Array.isArray(n.version)) return [...new Set(n.version)].sort((a, b) => a - b);
  if (typeof n.version === 'number') return [n.version];
  if (typeof n.defaultVersion === 'number') return [n.defaultVersion];
  return [1];
}

/** Extract enum values from an `options`-typed property, if present. */
function enumValues(prop: NodeProperty): string[] | undefined {
  if (prop.type !== 'options' || !Array.isArray(prop.options)) return undefined;
  const vals = prop.options
    .map((o) => (o && typeof o === 'object' && 'value' in o ? (o as { value: unknown }).value : undefined))
    .filter((v): v is string | number => typeof v === 'string' || typeof v === 'number')
    .map(String);
  return vals.length > 0 ? vals : undefined;
}

function nodeToSchema(n: NodeDescription, allVersions: number[]): NodeSchema {
  const required: Record<string, ParamType> = {};
  const optional: Record<string, ParamType> = {};
  const enums: Record<string, string[]> = {};
  for (const prop of n.properties ?? []) {
    if (!prop.name || prop.name === '') continue;
    const pt = toParamType(prop.type);
    // A property gated by displayOptions is only conditionally shown — treat as
    // optional to avoid false "missing required" on nodes using other modes.
    if (prop.required === true && !prop.displayOptions) required[prop.name] = pt;
    else optional[prop.name] = pt;
    const ev = enumValues(prop);
    if (ev) enums[prop.name] = ev;
  }
  const schema: NodeSchema = { typeVersion: allVersions, required, optional };
  if (Object.keys(enums).length > 0) schema.enums = enums;
  return schema;
}

/** Transform the live node list into the validator's NodeCatalog. */
export function transformToCatalog(nodes: NodeDescription[], host: string): NodeCatalog {
  // Aggregate every known version per type, then use the latest entry's schema.
  const versionsByType = new Map<string, Set<number>>();
  for (const n of nodes) {
    const set = versionsByType.get(n.name) ?? new Set<number>();
    for (const v of versionsOf(n)) set.add(v);
    versionsByType.set(n.name, set);
  }
  const latest = dedupeLatest(nodes);
  const out: Record<string, NodeSchema> = {};
  for (const n of latest) {
    const versions = [...(versionsByType.get(n.name) ?? new Set([1]))].sort((a, b) => a - b);
    out[n.name] = nodeToSchema(n, versions);
  }
  return {
    _meta: {
      version: '1.0-synced',
      generated: new Date().toISOString(),
      description: `Synced from ${host} (${Object.keys(out).length} node types)`,
      type_values: ['string', 'number', 'boolean', 'object', 'array', 'any'],
      notes: 'Generated by `n8nctl catalog sync` from the live instance /types/nodes.json.',
    },
    nodes: out,
  };
}

/** Node count of the validator's bundled catalog — the sanity-gate floor. */
export function bundledNodeCount(): number {
  const bundled = loadCatalog();
  return bundled ? Object.keys(bundled.nodes).length : 0;
}

/** Atomic write (temp + rename) so a crashed sync never leaves a half file. */
export async function writeSyncedCatalog(profileName: string, catalog: NodeCatalog): Promise<string> {
  const dest = syncedCatalogPath(profileName);
  await fs.mkdir(path.dirname(dest), { recursive: true });
  const tmp = `${dest}.tmp-${process.pid}`;
  await fs.writeFile(tmp, JSON.stringify(catalog, null, 2), 'utf8');
  await fs.rename(tmp, dest);
  return dest;
}

/**
 * Resolve the catalog the validator should use, most-specific first:
 *   1. explicit env path `N8N_VALIDATOR_CATALOG`
 *   2. the active profile's synced catalog
 *   3. null → caller lets the validator fall back to its bundled catalog
 */
export function resolveSyncedCatalog(profileName: string): NodeCatalog | null {
  const envPath = process.env.N8N_VALIDATOR_CATALOG;
  const file = envPath && envPath.trim() !== '' ? envPath : syncedCatalogPath(profileName);
  if (!existsSync(file)) return null;
  try {
    const parsed = JSON.parse(readFileSync(file, 'utf8')) as NodeCatalog;
    return parsed && parsed.nodes && typeof parsed.nodes === 'object' ? parsed : null;
  } catch {
    return null; // corrupt synced catalog → fall back to bundled, never crash
  }
}
